export const numbers = {
    english: {
        1: 'One',
        2: 'Two',
        3: 'Three',
        4: 'Four',
        5: 'Five',
        6: 'Six',
        7: 'Seven',
        8: 'Eight',
        9: 'Nine',
        10: 'Ten',
        11: 'Eleven',
        12: 'Twelve',
        13: 'Thirteen',
        14: 'Fourteen',
        15: 'Fifteen',
        16: 'Sixteen',
        17: 'Seventeen',
        18: 'Eighteen',
        19: 'Nineteen',
        20: 'Twenty',
        21: 'Twenty-One',
        22: 'Twenty-Two',
        23: 'Twenty-Three',
        24: 'Twenty-Four',
        25: 'Twenty-Five',
        26: 'Twenty-Six',
        27: 'Twenty-Seven',
        28: 'Twenty-Eight',
        29: 'Twenty-Nine',
        30: 'Thirty',
        31: 'Thirty-One',
        32: 'Thirty-Two',
        33: 'Thirty-Three',
        34: 'Thirty-Four',
        35: 'Thirty-Five',
        36: 'Thirty-Six',
        37: 'Thirty-Seven',
        38: 'Thirty-Eight',
        39: 'Thirty-Nine',
        40: 'Forty',
        41: 'Forty-One',
        42: 'Forty-Two',
        43: 'Forty-Three',
        44: 'Forty-Four',
        45: 'Forty-Five',
        46: 'Forty-Six',
        47: 'Forty-Seven',
        48: 'Forty-Eight',
        49: 'Forty-Nine',
        50: 'Fifty',
        51: 'Fifty-One',
        52: 'Fifty-Two',
        53: 'Fifty-Three',
        54: 'Fifty-Four',
        55: 'Fifty-Five',
        56: 'Fifty-Six',
        57: 'Fifty-Seven',
        58: 'Fifty-Eight',
        59: 'Fifty-Nine',
        60: 'Sixty',
        61: 'Sixty-One',
        62: 'Sixty-Two',
        63: 'Sixty-Three',
        64: 'Sixty-Four',
        65: 'Sixty-Five',
        66: 'Sixty-Six',
        67: 'Sixty-Seven',
        68: 'Sixty-Eight',
        69: 'Sixty-Nine',
        70: 'Seventy',
        71: 'Seventy-One',
        72: 'Seventy-Two',
        73: 'Seventy-Three',
        74: 'Seventy-Four',
        75: 'Seventy-Five',
        76: 'Seventy-Six',
        77: 'Seventy-Seven',
        78: 'Seventy-Eight',
        79: 'Seventy-Nine',
        80: 'Eighty',
        81: 'Eighty-One',
        82: 'Eighty-Two',
        83: 'Eighty-Three',
        84: 'Eighty-Four',
        85: 'Eighty-Five',
        86: 'Eighty-Six',
        87: 'Eighty-Seven',
        88: 'Eighty-Eight',
        89: 'Eighty-Nine',
        90: 'Ninety',
        91: 'Ninety-One',
        92: 'Ninety-Two',
        93: 'Ninety-Three',
        94: 'Ninety-Four',
        95: 'Ninety-Five',
        96: 'Ninety-Six',
        97: 'Ninety-Seven',
        98: 'Ninety-Eight',
        99: 'Ninety-Nine',
        100: 'One Hundred'
    },

    spanish: {
        1: 'Uno',
        2: 'Dos',
        3: 'Tres',
        4: 'Cuatro',
        5: 'Cinco',
        6: 'Seis',
        7: 'Siete',
        8: 'Ocho',
        9: 'Nueve',
        10: 'Diez',
        11: 'Once',
        12: 'Doce',
        13: 'Trece',
        14: 'Catorce',
        15: 'Quince',
        16: 'Dieciséis',
        17: 'Diecisiete',
        18: 'Dieciocho',
        19: 'Diecinueve',
        20: 'Veinte',
        21: 'Veintiuno',
        22: 'Veintidós',
        23: 'Veintitrés',
        24: 'Veinticuatro',
        25: 'Veinticinco',
        26: 'Veintiséis',
        27: 'Veintisiete',
        28: 'Veintiocho',
        29: 'Veintinueve',
        30: 'Treinta',
        31: 'Treinta y Uno',
        32: 'Treinta y Dos',
        33: 'Treinta y Tres',
        34: 'Treinta y Cuatro',
        35: 'Treinta y Cinco',
        36: 'Treinta y Seis',
        37: 'Treinta y Siete',
        38: 'Treinta y Ocho',
        39: 'Treinta y Nueve',
        40: 'Cuarenta',
        41: 'Cuarenta y Uno',
        42: 'Cuarenta y Dos',
        43: 'Cuarenta y Tres',
        44: 'Cuarenta y Cuatro',
        45: 'Cuarenta y Cinco',
        46: 'Cuarenta y Seis',
        47: 'Cuarenta y Siete',
        48: 'Cuarenta y Ocho',
        49: 'Cuarenta y Nueve',
        50: 'Cincuenta',
        51: 'Cincuenta y Uno',
        52: 'Cincuenta y Dos',
        53: 'Cincuenta y Tres',
        54: 'Cincuenta y Cuatro',
        55: 'Cincuenta y Cinco',
        56: 'Cincuenta y Seis',
        57: 'Cincuenta y Siete',
        58: 'Cincuenta y Ocho',
        59: 'Cincuenta y Nueve',
        60: 'Sesenta',
        61: 'Sesenta y Uno',
        62: 'Sesenta y Dos',
        63: 'Sesenta y Tres',
        64: 'Sesenta y Cuatro',
        65: 'Sesenta y Cinco',
        66: 'Sesenta y Seis',
        67: 'Sesenta y Siete',
        68: 'Sesenta y Ocho',
        69: 'Sesenta y Nueve',
        70: 'Setenta',
        71: 'Setenta y Uno',
        72: 'Setenta y Dos',
        73: 'Setenta y Tres',
        74: 'Setenta y Cuatro',
        75: 'Setenta y Cinco',
        76: 'Setenta y Seis',
        77: 'Setenta y Siete',
        78: 'Setenta y Ocho',
        79: 'Setenta y Nueve',
        80: 'Ochenta',
        81: 'Ochenta y Uno',
        82: 'Ochenta y Dos',
        83: 'Ochenta y Tres',
        84: 'Ochenta y Cuatro',
        85: 'Ochenta y Cinco',
        86: 'Ochenta y Seis',
        87: 'Ochenta y Siete',
        88: 'Ochenta y Ocho',
        89: 'Ochenta y Nueve',
        90: 'Noventa',
        91: 'Noventa y Uno',
        92: 'Noventa y Dos',
        93: 'Noventa y Tres',
        94: 'Noventa y Cuatro',
        95: 'Noventa y Cinco',
        96: 'Noventa y Seis',
        97: 'Noventa y Siete',
        98: 'Noventa y Ocho',
        99: 'Noventa y Nueve',
        100: 'Cien'
    }
};

export const numbersAmount = Object.keys(numbers.english).length;